resources:
  - url: /local/custom_ui/weather-card.js
    type: js
  - url: /local/custom_ui/dark-sky-weather-card.js?v=1
    type: js
 # - url: /local/custom_ui/monster-card.js
 #   type: js
  - url: /local/custom_ui/gauge-card.js
    type: js
  - url: /local/custom_ui/bignumber-card.js
    type: js
  - url: /local/custom_ui/alarm_control_panel-card.js?v=1
    type: js
  - url: /local/monster-card.js?v=1
    type: js
  - url: /local/group-card.js?v=2
    type: js  
  - url: /local/bignumber-card.js?v=0
    type: js
  - url: /local/tracker-card.js?v=0
    type: js
  - url: /local/thermostat-card.js?v=1
    type: module


title: Randy's Awesome Home
# Exclude entites from "Unused entities" view
excluded_entities:
  - weblink.router
views:
    # View tab title.
  - title: Tracker
    icon: mdi:account-multiple-outline
    # Optional unique id for direct access /lovelace/${id}
    id: RC Home
    # Each view can have a different theme applied.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      
      - type: custom:tracker-card
        title:
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
      
      - type: map
        entities:
        - entity: device_tracker.iphonerc
          name: RC
        - device_tracker.alexlustphone
        
        - device_tracker.kimiphone
      - type: entities
        title: Door Status
        entities:
        - binary_sensor.front_door_d3_
        - binary_sensor.deck_door_d6
        - binary_sensor.garage_door_d5_
        - binary_sensor.shed_door_
        - binary_sensor.side_garage_
        - binary_sensor.home_away
        - cover.big_gd
        - cover.small_gd
        - binary_sensor.pantry_door
        - binary_sensor.garage_door
      - type: entity-filter
        entities:
          - device_tracker.iphonerc
          - device_tracker.kimiphone
          - device_tracker.alexlustphone
        state_filter:
          - 'home'
        card_config:
          type: glance
          title: People that are home
      
      
      - type: entities
        entities:
          - device_tracker.iphonerc
          - device_tracker.kimiphone
          - device_tracker.alexlustphone
        
        card_config:
          type: glance
          title: People that are Away

        # The picture entity card will represent an entity with a picture
      - type: picture-entity
        entity: light.3162e3
        image: /local/images/1stfloorbig.png
        state_image:
          "on": /local/images/1stfloorbig.png
        title: Kitchen Cans
    
      
    # Specify a tab icon if you want the view tab to be an icon.
  - title: Room View
    cards:
      - type: custom:group-card
        card:
          type: entities
          title: Garage card
        group: group.garage_state
      - type: custom:group-card
        card:
          type: entities
          title: Master card
        group: group.master
      - type: custom:group-card
        card:
          type: entities
          title: Cars card
        group: group.carrs

      - type: custom:group-card
        card:
          type: entities
          title: Switch card
        group: group.all_switches

      - type: custom:group-card
        card:
          type: entities
          title: LED card
        group: group.led

      - type: picture-glance
        image: /local/images/1stfloorbig.png
        title: Garage
        entities:
          - switch.garage_big_state
          - switch.garage_small_open
          - switch.garage_small_state
          - cover.small_gd
          - cover.big_gd
          - binary_sensor.garage_door_d5_
          - binary_sensor.side_garage_door_status
          - binary_sensor.side_garage_
          - sensor.garage_temperature_2
          - sensor.garage_humidity_2
          - binary_sensor.garage_motion
          
  - title: Weather View
    icon: mdi:weather-partlycloudy
    # Title of the view. Will be used as the tooltip for tab icon
    
    cards:
      - type: history-graph
        hours_to_show: 48
        entities:
          - sensor.yweather_temperature
          - sensor.yweather_humidity
      - type: glance
        # Title of the entities card
        title: Yahoo Weather
        # The entities here will be shown in the same order as specified.
        # Each entriy is an entity ID or a map with extra options.
        entities:
          - sensor.yweather_current
          - sensor.yweather_condition
          - sensor.yweather_temperature
          - sensor.yweather_humidity
          - sensor.yweather_pressure
          - sensor.yweather_temperature_max
          - sensor.yweather_temperature_min
          - sensor.yweather_visibility
          - sensor.yweather_wind_speed
      - type: weather-forecast
        entity: weather.openweathermap

      - type: entities
        # Title of the entities card
        title: Nest
        # The entities here will be shown in the same order as specified.
        # Each entriy is an entity ID or a map with extra options.
        entities:
          - binary_sensor.family_room_thermostat_fan
          - binary_sensor.family_room_thermostat_has_leaf
          - binary_sensor.family_room_thermostat_is_locked
          - binary_sensor.family_room_thermostat_online
          - binary_sensor.family_room_thermostat_is_using_emergency_heat
          - climate.family_room
          - sensor.family_room_thermostat_humidity
          - sensor.family_room_thermostat_target
          - sensor.family_room_thermostat_temperature
          - sensor.family_room_thermostat_hvac_state
          - sensor.family_room_thermostat_operation_mode
      - type: custom:dark-sky-weather-card
        entity_sun: sun.sun
        entity_daily_summary: sensor.dark_sky_daily_summary
        entity_current_conditions: sensor.dark_sky_icon
        entity_humidity: sensor.dark_sky_humidity
        entity_pressure: sensor.dark_sky_pressure
        entity_temperature: sensor.dark_sky_temperature
        entity_visibility: sensor.dark_sky_visibility
        entity_wind_bearing: sensor.dark_sky_wind_bearing
        entity_wind_speed: sensor.dark_sky_wind_speed
        entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
        entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2
        entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3
        entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4
        entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5
        entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature
        entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1
        entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2
        entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3
        entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4
        entity_forecast_icon_1: sensor.dark_sky_icon_1
        entity_forecast_icon_2: sensor.dark_sky_icon_2
        entity_forecast_icon_3: sensor.dark_sky_icon_3
        entity_forecast_icon_4: sensor.dark_sky_icon_4
        entity_forecast_icon_5: sensor.dark_sky_icon_5


        # Entities card will take list of entities and show their state.
  
  - title: Home View
    icon: mdi:home
    # Title of the view. Will be used as the tooltip for tab icon
    
    cards:
        # Entities card will take list of entities and show their state.
      - type: glance
        # Title of the entities card
        title: Cars
        entities:
          - sensor.porsche_easy_batt_volt
          - sensor.bmw_temp
          - sensor.bmw_hum
          #
      # - type: history-graph
      #   hours_to_show: 8
      #   entities:
      #     - sensor.bmw_temp
      #     - sensor.bmw_hum
      - type: history-graph
        hours_to_show: 48
        entities:
          - sensor.bmw_temp
          - sensor.bmw_hum
          - sensor.porsche_easy_batt_volt    
      - type: glance
        # Title of the entities card
        title: Master
        entities:
          - light.2fc024
          - light.03e496
          - light.186156
          - sensor.fan_voltage
          - switch.fan
          #- sensor.esp32_hum
          #- sensor.esp32_temp
          - sensor.master_humidity
          - sensor.master_temperature
          - switch.master_restart
          - binary_sensor.master_esp32_status
          - switch.chandelier_2
      

      - type: glance
        title: System
        entities:
          - group.Memory
          - group.network
          - group.host_devices
          - group.host_device
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
          - sensor.download_iperfhenet
          - sensor.upload_iperfhenet



      - type: glance
                # Title of the entities card
        title: Doors Alarm
        # The entities here will be shown in the same order as specified.
        # Each entriy is an entity ID or a map with extra options.
        entities:
          - binary_sensor.garage_door_d5_
          - binary_sensor.deck_door_d6
          - binary_sensor.front_door_d3_
          - binary_sensor.shed_door_
          - binary_sensor.shed_esphome_status
          - sensor.shed_temperature
          - sensor.shed_humidity
          - switch.shed_esphome_restart

      - type: entities
        # Title of the entities card
        title: Lights
        icon: mdi.light-switch # The entities here will be shown in the same order as specified.
        # Each entriy is an entity ID or a map with extra options.
        entities:
          - light.1862ea
          - light.3162e3
          - light.07487f
          - light.2fc024
          - light.035b60
          - light.06f23e
          - light.07487f
          - light.186156
          - light.1862ea
          - light.2fc024
          - light.3162e3
          - light.316993
          - light.3df6f3
          - light.3dfafe
          - light.3e0379
          #- light.fireplace_basic_green_led
          - entity: light.2fc024
            # Override the name to use
            name: Master Bath
      
      - type: glance
        title: Sonoff Devices
        entities:
          - sensor.sonoff_01_version
          - sensor.sonoff_02_version
          - sensor.sonoff_03_version
          - sensor.sonoff_04_version
          - sensor.sonoff_05_version
          - sensor.sonoff_06_version
          - sensor.sonoff_07_version
          - sensor.sonoff_08_version
          - sensor.sonoff_09_version
          - sensor.sonoff_10_version
          - sensor.sonoff_11_version
          - sensor.sonoff_12_version
          - sensor.sonoff_latest_release

      - type: entities
        # Title of the entities card
        title: Switch
        # The entities here will be shown in the same order as specified.
        # Each entriy is an entity ID or a map with extra options.
        entities:
         # - group.all_switches
          - switch.16f884
          - switch.alarm_mcu_restart
          - switch.fireplace_basic_relay
          - switch.garage_motion_restart
          - switch.garage_restart
          - switch.master_restart
          #- switch.porsche_volt_restart
          - switch.shed_esphome_restart
          - switch.side_garage_restart

        

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
      - type: custom:monster-card
        card:
          type: glance
          title: Monster
        filter:
          include: [{}]
          exclude:
            - entity_id: "*yweather*"
            - domain: group
            - domain: zone    
      
      
      
  - title: Temperature View
    icon: mdi:oil-temperature
    # Title of the view. Will be used as the tooltip for tab icon
    
    cards:
      
      - type: custom:bignumber-card
        title: Temperature Outside
        entity: sensor.yweather_temperature
        scale: 30px
        from: bottom
        min: 0
        max: 100
        severity:
          - value: 70
            style: 'var(--label-badge-green)'
          - value: 90
            style: 'var(--label-badge-yellow)'
          - value: 100
            style: 'var(--label-badge-red)'
            
      - type: custom:bignumber-card
        title: Humidity Outside
        entity: sensor.yweather_humidity
        scale: 30px
        from: bottom
        min: 0
        max: 100
        severity:
          - value: 70
            style: 'var(--label-badge-green)'
          - value: 90
            style: 'var(--label-badge-yellow)'
          - value: 100
            style: 'var(--label-badge-red)'
            
      - type: custom:thermostat-card
        title: Nest
        entity: climate.family_room_2
        chevron_size: 100
        hvac:
          states:
            'Off': 'off'
            'Cooling': 'cool'
            'Heaing': 'heat'
          attribute: operation_mode
      
      - type: custom:monster-card
        card:
          type: glance
          title: Temperature Monster

        filter:
          include:
            - entity_id: "*temperature*"
           # - entity_id: "*humidity*"
            #- domain: sensor
          exclude:
            - entity_id: "*yweather*"
            - entity_id: "*dark*"
            - domain: group
            - domain: zone    
  - title: Entertainment View
    icon: mdi:television
    # Title of the view. Will be used as the tooltip for tab icon
    
    cards:

      - type: entities
        title: Remotes
        entities:
          - remote.cable_pwr_toggle
          
          - remote.onkyo_cblvideo2__bddvd
          - remote.onko_fire_tv__kodi
          - remote.onkyo_pwr
          - remote.tv_power
          - remote.family_room
      - type: custom:monster-card
        card:
          title: Media
          type: entities
          show_header_toggle: false
        filter:
          include:
            - domain: media_player
            - domain: camera
      - type: media-control  
        entity:  media_player.family_room_2
      - type: media-control  
        entity:  media_player.bathroom
      - type: media-control  
        entity:  media_player.kitchen
      - type: media-control  
        entity:  media_player.randys_fire_tv
      
      - type: media-control  
        entity: media_player.osmc

      - type: media-control  
        entity: media_player.viera_st60

      - type: media-control  
        entity: media_player.mpd

      - type: media-control  
        entity: media_player.frreceiver

      #- type: media-control
      #  entity: media_player.roku_13a18h054930

      - type: iframe
        url: http://192.168.1.164:32400/web
        aspect_ratio: 75%


  - title: Entertainment View 2
    icon: mdi:television
    # Title of the view. Will be used as the tooltip for tab icon
    
    cards:
        - type: entities
          title: Entertainment Options
          show_header_toggle: true
          entities:
            - type: call-service
              icon: mdi:power
              name: Led6 Couch light
              action_name: Toggle light
              service: light.toggle
              service_data:
                entity_id: light.led6
            - type: call-service
              icon: mdi:power
              name: Led2 TV light
              action_name: Toggle light
              service: light.toggle
              service_data:
                entity_id: light.tvled
            - type: divider
            - type: weblink
              name: Plex
              url: http://192.168.1.164:32400/web/index.html#
              icon: mdi:home-assistant
            
            - type: weblink
              name: Music Arch
              url: http://192.168.1.164:32400/web
              icon: mdi:music
