##############################################################################
# Automations to configure slider controls on page 4 as light dimmers
automation:
  - alias: hasp_plate04_p4_DimmersInit
    trigger:
    - platform: mqtt
      topic: 'hasp/plate04/status'
      payload: 'ON'
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/plate04/command/p[4].b[4].txt'
        payload: '"Light 1"'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate04/command/p[4].b[5].txt'
        payload: '"Light 2"'
    - service: mqtt.publish
      data:
        topic: 'hasp/plate04/command/p[4].b[6].txt'
        payload: '"Light 3"'
  
  - alias: hasp_plate04_p4_Dimmer7UpdateHass
    trigger:
    - platform: mqtt
      topic: 'hasp/plate04/state/p[4].b[7].val'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.light_1
        brightness: '{{ trigger.payload }}'
  
  - alias: hasp_plate04_p4_Dimmer7UpdateHASP
    trigger:
    - platform: state
      entity_id: light.light_1
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate04/command/p[4].b[7].val'
        payload_template: '{{states.light.light_1.attributes.brightness|default(0)|int}}'
  
  - alias: hasp_plate04_p4_Dimmer8UpdateHass
    trigger:
    - platform: mqtt
      topic: 'hasp/plate04/state/p[4].b[8].val'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.light_2
        brightness: '{{ trigger.payload }}'
  
  - alias: hasp_plate04_p4_Dimmer8UpdateHASP
    trigger:
    - platform: state
      entity_id: light.light_2
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate04/command/p[4].b[8].val'
        payload_template: '{{states.light.light_2.attributes.brightness|default(0)|int}}'
  
  - alias: hasp_plate04_p4_Dimmer9UpdateHass
    trigger:
    - platform: mqtt
      topic: 'hasp/plate04/state/p[4].b[9].val'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.light_3
        brightness: '{{ trigger.payload }}'
  
  - alias: hasp_plate04_p4_Dimmer9UpdateHASP
    trigger:
    - platform: state
      entity_id: light.light_3
    action:
    - service: mqtt.publish
      data_template:
        topic: 'hasp/plate04/command/p[4].b[9].val'
        payload_template: '{{states.light.light_3.attributes.brightness|default(0)|int}}'