- platform: yr

- platform: mqtt
  state_topic: '/porsche/Voltage'
  name: 'Porsche Easy Batt Volt'
  unit_of_measurement: 'V'
  
- platform: mqtt
  state_topic: '/ESP_Easy32/TempH/Temperature'
  name: 'ESP32 Temp'
  unit_of_measurement: '°C'
- platform: mqtt
  state_topic: '/ESP_Easy32/TempH/Humidity'
  name: 'ESP32 Hum'
  unit_of_measurement: '%'
  
- platform: mqtt
  state_topic: 'tele/attic/SENSOR'
  name: 'Attic Temp'
  unit_of_measurement: '°F'
  value_template: "{{ value_json['AM2301'].Temperature }}"

- platform: mqtt
  state_topic: 'tele/attic/SENSOR'
  name: 'Attic Hum'
  unit_of_measurement: '%'
  value_template: "{{ value_json['AM2301'].Humidity }}"

- platform: mqtt
  state_topic: '/hooks/devices/base/SensorData/Water'
  name: 'Hot Water Pipe'
  unit_of_measurement: '°C'
  # value_template: '{{ value_json.DHT.Temperature }}' 

- platform: mqtt
  state_topic: '/hooks/devices/base/SensorData/Duct'
  name: 'Duct Temp'
  unit_of_measurement: '°C'

- platform: mqtt
  state_topic: '/hooks/devices/bmw/SensorData/Temperature'
  name: 'BMW Temp'
  unit_of_measurement: '°F'

- platform: mqtt
  state_topic: '/hooks/devices/bmw/SensorData/Switch'
  name: 'BMW Switch'

  #unit_of_measurement: '°F'
- platform: mqtt
  state_topic: '/hooks/devices/bmw/SensorData/Humidity'
  name: 'BMW Hum'
  unit_of_measurement: '%' 
- platform: darksky
  api_key: 9687683ab89181d52cb96254af23ca08
  forecast:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  monitored_conditions:
    - summary
    - precip_probability
    - wind_speed
    - cloud_cover
    - icon
    - temperature_low
    - temperature_high
    - daily_summary
    - hourly_summary
    - humidity
    - temperature
    - wind_bearing
    - pressure
    - visibility
  update_interval:
    minutes: 5

- platform: season
- platform: template
  sensors:
    forecast_0:
      friendly_name: "Today"
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon.state ~ '.png'}}
    forecast_1:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
        {{ date | timestamp_custom("Tomorrow (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_1.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_1.state ~ '.png'}}
    forecast_2:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
        {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_2.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_2.state ~ '.png'}}
    forecast_3:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
        {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_3.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_3.state ~ '.png'}}
    forecast_4:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
        {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_4.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_4.state ~ '.png'}}
    forecast_5:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
        {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
      value_template: >
        {{states.sensor.dark_sky_daytime_high_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_5.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_5.state ~ '.png'}}
    forecast_6:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
        {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
      value_template: >
          {{states.sensor.dark_sky_daytime_high_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_6.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_6.state ~ '.png'}}
    forecast_7:
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (7 * 86400 ) -%}
        {{ date | timestamp_custom("%A (%m/%d)") | replace("(0", "(") | replace("/0", "/") }}
      value_template: >
          {{states.sensor.dark_sky_daytime_high_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_overnight_low_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_7.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_7.state ~ '.png'}}

- platform: darksky 
  api_key: 9687683ab89181d52cb96254af23ca08
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    # - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max

# Monitor host system
- platform: systemmonitor
  resources:
  - type: disk_use_percent
    arg: /home
  - type: memory_free
  - type: processor_use
  - type: last_boot
  - type: memory_use
  - type: memory_use_percent

# Monitor host cpu temp
- platform: command_line
  name: CPU Temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value|multiply(0.001)|round }}'

# Speedtest.net
- platform: speedtest
  minute:
    - 17
  # hour:
    # - 0
    # - 4
    # - 8
    # - 12
    # - 16
    # - 20
  monitored_conditions:
    - ping
    - download
    - upload
