##############################################################################
# The devices created below are essential to the page control automations
# and you'll probably want to carry them over to your own configuration
homeassistant:
  customize:
    input_number.hasp_plate03_alarmcode1:
      hidden: true
    input_number.hasp_plate03_alarmcode2:
      hidden: true
    input_number.hasp_plate03_alarmcode3:
      hidden: true
    input_number.hasp_plate03_alarmcode4:
      hidden: true

# Enable this iframe to integrate the HASP web admin panel in Hass.
# This will not work if you have SSL enabled, see details here:
# https://www.home-assistant.io/components/panel_iframe/
#
panel_iframe:
  plate03:
    title: "plate03"
    url: "http://plate03.local"
    icon: "mdi:cellphone-text"

light:
  - platform: mqtt
    name: plate03 Backlight
    command_topic: "hasp/plate03/light/switch"
    state_topic: "hasp/plate03/light/status"
    brightness_state_topic: "hasp/plate03/brightness/status"
    brightness_command_topic: "hasp/plate03/brightness/set"

binary_sensor:
  - platform: mqtt
    name: plate03 Connected
    device_class: connectivity
    state_topic: "hasp/plate03/status"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "hasp/plate03/status"
    payload_available: "ON"
    payload_not_available: "OFF"

sensor:
  - platform: mqtt
    name: plate03 Sensor
    state_topic: "hasp/plate03/sensor"
    value_template: '{{ value_json.status }}'
    json_attributes:
      - espVersion
      - updateESPAvailable
      - lcdVersion
      - updateLcdAvailable
      - espUptime
      - signalStrength
      - haspIP

input_text:
  hasp_plate03_pagebutton1label:
    name: plate03 Page 1 Label
    icon: mdi:book-open-page-variant
    initial: Scene
  hasp_plate03_pagebutton2label:
    name: plate03 Page 2 Label
    icon: mdi:book-open-page-variant
    initial: Status
  hasp_plate03_pagebutton3label:
    name: plate03 Page 3 Label
    icon: mdi:book-open-page-variant
    initial: Music

input_number:
  hasp_plate03_pagebutton1page:
    name: plate03 Page 1 Page
    icon: mdi:format-list-numbers
    initial: 1
    min: 0
    max: 9
    step: 1
  hasp_plate03_pagebutton2page:
    name: plate03 Page 2 Page
    icon: mdi:format-list-numbers
    initial: 2
    min: 0
    max: 9
    step: 1
  hasp_plate03_pagebutton3page:
    name: plate03 Page 3 Page
    icon: mdi:format-list-numbers
    initial: 8
    min: 0
    max: 9
    step: 1
  hasp_plate03_activepage:
    name: plate03 Active Page
    icon: mdi:format-list-numbers
    initial: 2
    min: 0
    max: 9
    step: 1
  hasp_plate03_alarmcode1:
    name: plate03 AlarmCode1
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_plate03_alarmcode2:
    name: plate03 AlarmCode2
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_plate03_alarmcode3:
    name: plate03 AlarmCode3
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_plate03_alarmcode4:
    name: plate03 AlarmCode4
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1

group:
  plate03:
    name: plate03
    view: yes
    entities:
      - binary_sensor.plate03_connected
      - sensor.plate03_sensor
      - light.plate03_backlight
      - group.plate03_pageselect
      - group.plate03_automations
  plate03_pageselect:
    name: plate03 Page Selection
    view: no
    entities:
      - input_number.hasp_plate03_activepage
      - input_number.hasp_plate03_pagebutton1page
      - input_text.hasp_plate03_pagebutton1label
      - input_number.hasp_plate03_pagebutton2page
      - input_text.hasp_plate03_pagebutton2label
      - input_number.hasp_plate03_pagebutton3page
      - input_text.hasp_plate03_pagebutton3label
  plate03_automations:
    name: plate03 automations
    view: no
    entities:
      - automation.hasp_plate03_00_firsttimesetup
      - automation.hasp_plate03_00_autofirmwareupdate
      - automation.hasp_plate03_p0_activepagesliderchanged
      - automation.hasp_plate03_p0_pagebutton1_text
      - automation.hasp_plate03_p0_pagebutton1action
      - automation.hasp_plate03_p0_pagebutton2_text
      - automation.hasp_plate03_p0_pagebutton2action
      - automation.hasp_plate03_p0_pagebutton3_text
      - automation.hasp_plate03_p0_pagebutton3action
      - automation.hasp_plate03_p0_pagebuttoncolors
      - automation.hasp_plate03_p0_panelpagechanged
      - automation.hasp_plate03_p0_restoreactivepage
      - automation.hasp_plate03_p1_scenebutton4
      - automation.hasp_plate03_p1_scenebutton5
      - automation.hasp_plate03_p1_scenebutton6
      - automation.hasp_plate03_p1_scenebutton7
      - automation.hasp_plate03_p1_scenesinit
      - automation.hasp_plate03_p2_clockinit
      - automation.hasp_plate03_p2_clockupdate
      - automation.hasp_plate03_p2_calendarupdate
      - automation.hasp_plate03_p2_weather
      - automation.hasp_plate03_p3_toggleall
      - automation.hasp_plate03_p3_togglecolor1
      - automation.hasp_plate03_p3_togglecolor2
      - automation.hasp_plate03_p3_togglecolor3
      - automation.hasp_plate03_p3_togglecolorall
      - automation.hasp_plate03_p3_toggleinit
      - automation.hasp_plate03_p3_togglelight1
      - automation.hasp_plate03_p3_togglelight2
      - automation.hasp_plate03_p3_togglelight3
      - automation.hasp_plate03_p4_dimmer7updatehasp
      - automation.hasp_plate03_p4_dimmer7updatehass
      - automation.hasp_plate03_p4_dimmer8updatehasp
      - automation.hasp_plate03_p4_dimmer8updatehass
      - automation.hasp_plate03_p4_dimmer9updatehasp
      - automation.hasp_plate03_p4_dimmer9updatehass
      - automation.hasp_plate03_p4_dimmersinit
      - automation.hasp_plate03_p7_alarmarm
      - automation.hasp_plate03_p7_alarmarmed
      - automation.hasp_plate03_p7_alarmcodeentry0
      - automation.hasp_plate03_p7_alarmcodeentry1to9
      - automation.hasp_plate03_p7_alarmdisarm
      - automation.hasp_plate03_p7_alarmdisarmed
      - automation.hasp_plate03_p7_alarminit
      - automation.hasp_plate03_p7_alarmstatuspending
      - automation.hasp_plate03_p8_mediaartist
      - automation.hasp_plate03_p8_mediainit
      - automation.hasp_plate03_p8_medianexttrackbutton8
      - automation.hasp_plate03_p8_mediapausebutton7
      - automation.hasp_plate03_p8_mediaplaypause
      - automation.hasp_plate03_p8_mediaprevtrackbutton6
      - automation.hasp_plate03_p8_mediatitle
      - automation.hasp_plate03_p8_mediavolsliderupdatehasp
      - automation.hasp_plate03_p8_mediavolsliderupdatehass
      - automation.hasp_plate03_p9_3dprinterinit
      - automation.hasp_plate03_p9_3dprinteroperational
      - automation.hasp_plate03_p9_3dprinterpaused
      - automation.hasp_plate03_p9_3dprinterprinting
      - automation.hasp_plate03_p9_3dprintertempgraph
      - automation.hasp_plate03_p9_3dprintertemptext

automation:
##############################################################################
# Set default values for input_text/number sliders
  - alias: hasp_plate03_00_FirstTimeSetup
    trigger: []
    action:
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_plate03_pagebutton1label'
          value: 'scenes'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_plate03_pagebutton2label'
          value: 'status'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_plate03_pagebutton3label'
          value: 'lights'
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_plate03_pagebutton1page'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_plate03_pagebutton2page'
          value: 2
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_plate03_pagebutton3page'
          value: 3
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_plate03_activepage'
          value: 1